[peer]

# The address and port your server will bind to.
bind_addr = "127.0.0.1:4141"

# Database path.
db_path = "assets/peers.sqlite3"

# Path to file with pub/priv key pair.
key_path = "assets/keys_peer.bullet"

bootstraps = [[127,0,0,1]]

# Maximum number of active TCP connections allowed.
max_connections = 512

# How many buffers of size max_buffer_size net_man holds.
buffers_cap = 512

# The maximum buffer size per connection (in bytes).
max_buffer_size = 2048

# Capacity of inbound and outbound msg queue per connection.
conn_q_cap = 32

# Time (in seconds) before closing an idle connection.
idle_timeout = 2 

# Poll timeout (in milliseconds) for idle network polls.
idle_polltimeout = 100

# The capacity of your event buffer (e.g., for epoll events).
poll_event_cap = 512

# The score at which a peer becomes banned.
peer_threshold = 200



[blockchain]
# Poll timeout (in milliseconds) for idle core tasks.
idle_polltimeout = 100

# Initial transaction buffer length (e.g., preallocated task queue size).
init_trx_len = 512

# Event queue capacity (used for cross-actor event passing).
event_len = 128

# TRX pool capacity.
pool_cap = 8

# How many bulletproofs to validate at once
bullet_count = 1

epoch_interval = 240

# Ledger path.
ledger_path = "assets/ledger"

# Ledger cache size.
ledger_cache_size = 256

# Ledger size == 10GB
ledger_map_size = 10_000_000_000

# Ledger domain specific tag.
ledger_tag = "bullet_ledger"

# Block Size == 2Mb
block_size = 2_000_000




[rpc]
# The address and port your server will bind to.
bind_addr = "127.0.0.1:4040"

# Database path.
db_path = "assets/rpc.sqlite3"

# Path to file with pub/priv key pair.
key_path = "assets/keys_rpc.bullet"

bootstraps = [[127,0,0,1]]

# Maximum number of active TCP connections allowed.
max_connections = 512

# How many buffers of size max_buffer_size net_man holds.
buffers_cap = 512

# The maximum buffer size per connection (in bytes).
max_buffer_size = 2048

# Capacity of inbound and outbound msg queue per connection.
conn_q_cap = 32

# The capacity of your event buffer (e.g., for epoll events).
poll_event_cap = 512

# Time (in seconds) before closing an idle connection.
idle_timeout = 2 

# Poll timeout (in milliseconds) for idle network polls.
idle_polltimeout = 100


[social]

# Poll timeout (in milliseconds) for idle network polls.
idle_polltimeout = 100

# Event queue capacity (used for cross-actor event passing).
event_len = 128
